# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/arianna1/Desktop/ECE520/csun-ece/fa22-e520-lab4-ece520_fa22_group1/hardware/constr/Zybo-Z7-IO.xdc

# Block Designs: bd/tmp_sens_bd/tmp_sens_bd.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tmp_sens_bd || ORIG_REF_NAME==tmp_sens_bd} -quiet] -quiet

# IP: bd/tmp_sens_bd/ip/tmp_sens_bd_processing_system7_0_0/tmp_sens_bd_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tmp_sens_bd_processing_system7_0_0 || ORIG_REF_NAME==tmp_sens_bd_processing_system7_0_0} -quiet] -quiet

# IP: bd/tmp_sens_bd/ip/tmp_sens_bd_axi_uartlite_0_0/tmp_sens_bd_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tmp_sens_bd_axi_uartlite_0_0 || ORIG_REF_NAME==tmp_sens_bd_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/tmp_sens_bd/ip/tmp_sens_bd_xbar_0/tmp_sens_bd_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tmp_sens_bd_xbar_0 || ORIG_REF_NAME==tmp_sens_bd_xbar_0} -quiet] -quiet

# IP: bd/tmp_sens_bd/ip/tmp_sens_bd_ps7_0_axi_periph_0/tmp_sens_bd_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tmp_sens_bd_ps7_0_axi_periph_0 || ORIG_REF_NAME==tmp_sens_bd_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/tmp_sens_bd/ip/tmp_sens_bd_rst_ps7_0_50M_0/tmp_sens_bd_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tmp_sens_bd_rst_ps7_0_50M_0 || ORIG_REF_NAME==tmp_sens_bd_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/tmp_sens_bd/ip/tmp_sens_bd_PmodTMP3_0_0/tmp_sens_bd_PmodTMP3_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tmp_sens_bd_PmodTMP3_0_0 || ORIG_REF_NAME==tmp_sens_bd_PmodTMP3_0_0} -quiet] -quiet

# IP: /home/arianna1/Desktop/ECE520/csun-ece/fa22-e520-lab4-ece520_fa22_group1/hardware/tmp_uart_proj/tmp_uart_proj.gen/sources_1/bd/tmp_sens_bd/ip/tmp_sens_bd_PmodTMP3_0_0/src/PmodTMP3_xlconstant_0_0/PmodTMP3_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodTMP3_xlconstant_0_0 || ORIG_REF_NAME==PmodTMP3_xlconstant_0_0} -quiet] -quiet

# IP: /home/arianna1/Desktop/ECE520/csun-ece/fa22-e520-lab4-ece520_fa22_group1/hardware/tmp_uart_proj/tmp_uart_proj.gen/sources_1/bd/tmp_sens_bd/ip/tmp_sens_bd_PmodTMP3_0_0/src/PmodTMP3_pmod_bridge_0_0/PmodTMP3_pmod_bridge_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodTMP3_pmod_bridge_0_0 || ORIG_REF_NAME==PmodTMP3_pmod_bridge_0_0} -quiet] -quiet

# IP: /home/arianna1/Desktop/ECE520/csun-ece/fa22-e520-lab4-ece520_fa22_group1/hardware/tmp_uart_proj/tmp_uart_proj.gen/sources_1/bd/tmp_sens_bd/ip/tmp_sens_bd_PmodTMP3_0_0/src/PmodTMP3_axi_iic_0_0/PmodTMP3_axi_iic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodTMP3_axi_iic_0_0 || ORIG_REF_NAME==PmodTMP3_axi_iic_0_0} -quiet] -quiet

# IP: bd/tmp_sens_bd/ip/tmp_sens_bd_xlconcat_0_0/tmp_sens_bd_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tmp_sens_bd_xlconcat_0_0 || ORIG_REF_NAME==tmp_sens_bd_xlconcat_0_0} -quiet] -quiet

# IP: bd/tmp_sens_bd/ip/tmp_sens_bd_auto_pc_0/tmp_sens_bd_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tmp_sens_bd_auto_pc_0 || ORIG_REF_NAME==tmp_sens_bd_auto_pc_0} -quiet] -quiet

# XDC: /home/arianna1/Desktop/ECE520/csun-ece/fa22-e520-lab4-ece520_fa22_group1/hardware/tmp_uart_proj/tmp_uart_proj.gen/sources_1/bd/tmp_sens_bd/ip/tmp_sens_bd_processing_system7_0_0/tmp_sens_bd_processing_system7_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==tmp_sens_bd_processing_system7_0_0 || ORIG_REF_NAME==tmp_sens_bd_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/arianna1/Desktop/ECE520/csun-ece/fa22-e520-lab4-ece520_fa22_group1/hardware/tmp_uart_proj/tmp_uart_proj.gen/sources_1/bd/tmp_sens_bd/ip/tmp_sens_bd_axi_uartlite_0_0/tmp_sens_bd_axi_uartlite_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==tmp_sens_bd_axi_uartlite_0_0 || ORIG_REF_NAME==tmp_sens_bd_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/arianna1/Desktop/ECE520/csun-ece/fa22-e520-lab4-ece520_fa22_group1/hardware/tmp_uart_proj/tmp_uart_proj.gen/sources_1/bd/tmp_sens_bd/ip/tmp_sens_bd_axi_uartlite_0_0/tmp_sens_bd_axi_uartlite_0_0_ooc.xdc

# XDC: /home/arianna1/Desktop/ECE520/csun-ece/fa22-e520-lab4-ece520_fa22_group1/hardware/tmp_uart_proj/tmp_uart_proj.gen/sources_1/bd/tmp_sens_bd/ip/tmp_sens_bd_axi_uartlite_0_0/tmp_sens_bd_axi_uartlite_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==tmp_sens_bd_axi_uartlite_0_0 || ORIG_REF_NAME==tmp_sens_bd_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/arianna1/Desktop/ECE520/csun-ece/fa22-e520-lab4-ece520_fa22_group1/hardware/tmp_uart_proj/tmp_uart_proj.gen/sources_1/bd/tmp_sens_bd/ip/tmp_sens_bd_rst_ps7_0_50M_0/tmp_sens_bd_rst_ps7_0_50M_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==tmp_sens_bd_rst_ps7_0_50M_0 || ORIG_REF_NAME==tmp_sens_bd_rst_ps7_0_50M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/arianna1/Desktop/ECE520/csun-ece/fa22-e520-lab4-ece520_fa22_group1/hardware/tmp_uart_proj/tmp_uart_proj.gen/sources_1/bd/tmp_sens_bd/ip/tmp_sens_bd_rst_ps7_0_50M_0/tmp_sens_bd_rst_ps7_0_50M_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==tmp_sens_bd_rst_ps7_0_50M_0 || ORIG_REF_NAME==tmp_sens_bd_rst_ps7_0_50M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/arianna1/Desktop/ECE520/csun-ece/fa22-e520-lab4-ece520_fa22_group1/hardware/tmp_uart_proj/tmp_uart_proj.gen/sources_1/bd/tmp_sens_bd/ip/tmp_sens_bd_PmodTMP3_0_0/src/PmodTMP3_pmod_bridge_0_0/PmodTMP3_pmod_bridge_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodTMP3_pmod_bridge_0_0 || ORIG_REF_NAME==PmodTMP3_pmod_bridge_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/arianna1/Desktop/ECE520/csun-ece/fa22-e520-lab4-ece520_fa22_group1/hardware/tmp_uart_proj/tmp_uart_proj.gen/sources_1/bd/tmp_sens_bd/ip/tmp_sens_bd_PmodTMP3_0_0/src/PmodTMP3_pmod_bridge_0_0/src/pmod_concat_ooc.xdc

# XDC: /home/arianna1/Desktop/ECE520/csun-ece/fa22-e520-lab4-ece520_fa22_group1/hardware/tmp_uart_proj/tmp_uart_proj.gen/sources_1/bd/tmp_sens_bd/ip/tmp_sens_bd_PmodTMP3_0_0/src/PmodTMP3_axi_iic_0_0/PmodTMP3_axi_iic_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodTMP3_axi_iic_0_0 || ORIG_REF_NAME==PmodTMP3_axi_iic_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/arianna1/Desktop/ECE520/csun-ece/fa22-e520-lab4-ece520_fa22_group1/hardware/tmp_uart_proj/tmp_uart_proj.gen/sources_1/bd/tmp_sens_bd/ip/tmp_sens_bd_PmodTMP3_0_0/src/PmodTMP3_axi_iic_0_0/PmodTMP3_axi_iic_0_0_ooc.xdc

# XDC: /home/arianna1/Desktop/ECE520/csun-ece/fa22-e520-lab4-ece520_fa22_group1/hardware/tmp_uart_proj/tmp_uart_proj.gen/sources_1/bd/tmp_sens_bd/ip/tmp_sens_bd_PmodTMP3_0_0/tmp_sens_bd_PmodTMP3_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==tmp_sens_bd_PmodTMP3_0_0 || ORIG_REF_NAME==tmp_sens_bd_PmodTMP3_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/arianna1/Desktop/ECE520/csun-ece/fa22-e520-lab4-ece520_fa22_group1/hardware/tmp_uart_proj/tmp_uart_proj.gen/sources_1/bd/tmp_sens_bd/ip/tmp_sens_bd_PmodTMP3_0_0/src/PmodTMP3_ooc.xdc

# XDC: /home/arianna1/Desktop/ECE520/csun-ece/fa22-e520-lab4-ece520_fa22_group1/hardware/tmp_uart_proj/tmp_uart_proj.gen/sources_1/bd/tmp_sens_bd/ip/tmp_sens_bd_auto_pc_0/tmp_sens_bd_auto_pc_0_ooc.xdc

# XDC: /home/arianna1/Desktop/ECE520/csun-ece/fa22-e520-lab4-ece520_fa22_group1/hardware/tmp_uart_proj/tmp_uart_proj.gen/sources_1/bd/tmp_sens_bd/tmp_sens_bd_ooc.xdc
